### ISSUE TITLE
Optimize how we deal with git

### ISSUE THREAD

**Issue by tc80** [cdnjs/tools#206]
The git repo is big and so git operations are slow.

Random ideas
- integrate [go-git](https://git-scm.com/book/en/v2/Appendix-B%3A-Embedding-Git-in-your-Applications-go-git) library
- parallel processing of packages (will need to ensure we can read logs!)
- break up git repo somehow? maybe we don't want 4000 submodules but maybe we can break it up...
- investigate [Git LFS (Large File Storage)](https://git-lfs.github.com/)
- use of [git sparse-checkout](https://git-scm.com/docs/git-sparse-checkout) -- what if we ran a separate light-weight process per package that only checked out the files from the repo for that package?

**Comment by xtuc** [comment]
Pushing in git has been optimized
