### ISSUE TITLE
npm invalid "dist-tags"

### ISSUE THREAD

**Issue by tc80** [cdnjs/tools#52]
The `dist-tags` on `angularjs-ie8-build` appears to be invalid, containing `[latest]` instead of the expected `latest` property.

Action items:

- need to contact npm
- or, update implementation to handle bad packages

https://registry.npmjs.org/angularjs-ie8-build

**Comment by MattIPv4** [comment]
Worth also noting that this breaks their frontend site: https://www.npmjs.com/package/angularjs-ie8-build

**Comment by xtuc** [comment]
Did anyone reached out yet?

**Comment by MattIPv4** [comment]
I haven't

**Comment by xtuc** [comment]
For the record, I  DMed npm support on Twitter

**Comment by tc80** [comment]
included in #66
