### ISSUE TITLE
Inconsistencies with npm registry API

### ISSUE THREAD

**Issue by tc80** [cdnjs/tools#66]
There were a number of issues found when querying the [npm registry API](https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md).

### Contains `tags` instead of `dist-tags`
[Camera](https://registry.npmjs.org/Camera)
[Glide.js](https://registry.npmjs.org/Glide.js)
[HTML5Notification](https://registry.npmjs.org/HTML5Notification)
[Vue2Leaflet](https://registry.npmjs.org/Vue2Leaflet)
[angular-filemanager](https://registry.npmjs.org/angular-filemanager)
[apng-canvas](https://registry.npmjs.org/apng-canvas)
[backbone-tastypie](https://registry.npmjs.org/backbone-tastypie)
[blueprintjs-core](https://registry.npmjs.org/blueprintjs-core)
[buy-button-js](https://registry.npmjs.org/buy-button-js)
[custom-elements-builder](https://registry.npmjs.org/custom-elements-builder)
[domplotter](https://registry.npmjs.org/domplotter)
[elevatezoom](https://registry.npmjs.org/elevatezoom)
[joyride](https://registry.npmjs.org/joyride)
[joyride](https://registry.npmjs.org/joyride)
[js-xss](https://registry.npmjs.org/js-xss)
[lazyad-loader](https://registry.npmjs.org/lazyad-loader)
[oppia](https://registry.npmjs.org/oppia)
[requirejs-mustache](https://registry.npmjs.org/requirejs-mustache)
[responsive-elements](https://registry.npmjs.org/responsive-elements)
[roslibjs](https://registry.npmjs.org/roslibjs)
[signalr.js](https://registry.npmjs.org/signalr.js)
[techan.js](https://registry.npmjs.org/techan.js)

### Contains `[latest]` instead of `latest`
[angularjs-ie8-build](https://registry.npmjs.org/angularjs-ie8-build)

### Missing `time`
[json2](https://registry.npmjs.org/json2)

### Missing `latest`
[livestamp](https://registry.npmjs.org/livestamp)

**Comment by MattIPv4** [comment]
Do we have a contact at NPM that we can loop in here? I feel it might be more productive to be able to track this here with folks from NPM than via a support ticket or Twitter DM if possible?

**Comment by xtuc** [comment]
@MattIPv4  we reached out to npm

**Comment by tc80** [comment]
we are no longer using the `latest` tag, just pure time stamps. For `json2` this was here as a mistake, since the source is [git](https://github.com/douglascrockford/JSON-js), not npm.
