### ISSUE TITLE
Support operating on sparse-checkout of cdnjs

### ISSUE THREAD

**Issue by klausenbusk** [cdnjs/tools#75]
Cloning the [`cdnjs` repository](https://github.com/cdnjs/cdnjs) is a very expensive operation, as the repository is very big (11GB (compressed) at the time of writing, [100GB+ checked out](https://twitter.com/zackbloom/status/1171155443554689027)) and contains a lot of files. Often we only need the `package.json` files and the directory tree, but not the actual file content of all the stored versions. If we ever want to switch to ex: GitHub Actions (https://github.com/cdnjs/bot-ansible/issues/11) we need this.

Combing [partial clone](https://git-scm.com/docs/partial-clone) and [sparse checkout](https://git-scm.com/docs/git-sparse-checkout) is much faster:
```
$ time git clone --filter=blob:none --sparse git@github.com:cdnjs/cdnjs.git
[...]
real	1m18,731s
$ cd cdnjs
$ time git sparse-checkout add '**/package.json'
[..]
real	0m24,713s
$ find | head -n 10
.
./ajax
./ajax/libs
./ajax/libs/zxcvbn
./ajax/libs/zxcvbn/package.json
./ajax/libs/zurb-ink
./ajax/libs/zurb-ink/package.json
./ajax/libs/zumper-angular-payments
./ajax/libs/zumper-angular-payments/package.json
$ du -hs
1,1G	
```

---

Looking at the code, we need to change this code, so it also checks the tree (`git ls-tree`) (something similar to #67):
https://github.com/cdnjs/tools/blob/1928a3cca55a4f64c34fbbefabde74e90c57c52d/cmd/autoupdate/git.go#L113-L116
This code need to run `git sparse-checkout add <PATH>` first (if `core.sparseCheckout` is true):
https://github.com/cdnjs/tools/blob/1928a3cca55a4f64c34fbbefabde74e90c57c52d/packages/packages.go#L96-L98
This code need to be changed, so it doesn't get the existing versions from the filesystem but from the tree (`git ls-tree`):
https://github.com/cdnjs/tools/blob/1928a3cca55a4f64c34fbbefabde74e90c57c52d/packages/git.go#L15-L18
^ @xtuc was it implemented this way on purpose? (https://github.com/cdnjs/tools/commit/613817277c9dcbd184c135050d73fc88e0973213#diff-2538e4c3ee0b09db855e7569a1865cc2R16) Why do it stat the filesystem, wouldn't it be easier just to rely on `git ls-tree`?

/refs https://github.com/cdnjs/bot-ansible/issues/11

**Comment by xtuc** [comment]
The bot wasn't designed by me/us, I rewrote it.
To be clear, we are not planning to optimize git because we are working to move away from it eventually.

**Comment by klausenbusk** [comment]
>  To be clear, we are not planning to optimize git because we are working to move away from it eventually.

Fair enough :)
