### ISSUE TITLE
`package.json` is updated even though `latestVersion` wasn't added

### ISSUE THREAD

**Issue by klausenbusk** [cdnjs/tools#99]
xterm: https://github.com/cdnjs/cdnjs/commit/fa4788c7269db5f77392880ee576de0c661ef17e
Faker: https://github.com/cdnjs/cdnjs/commit/7720617953c4bc07ff27035a3a093b38ffffe1d0

Both of them have a broken autoupdate config ([xterm](https://gist.githubusercontent.com/klausenbusk/12a43115b06878937dba57b2f64cdaf7/raw/2417378c9fb7f4cca5871a228ff21fbfe3468d17/xterm.json), [Faker](https://gist.githubusercontent.com/klausenbusk/12a43115b06878937dba57b2f64cdaf7/raw/2417378c9fb7f4cca5871a228ff21fbfe3468d17/Faker.json))

This probably explains cdnjs/packages#337 and cdnjs/packages#338. I think the issue is caused by #79 

/refs cdnjs/packages#302
/cc @tc80

**Comment by tc80** [comment]
aw man! I'll check it out, thanks

**Comment by tc80** [comment]
Yep, you're right. `xterm` is looking for files in `dist/` which doesn't exist in the recent versions. Latest version needs to change to latest existing version

**Comment by tc80** [comment]
Can you have a look at my PR? 

I think it should fix these existing cases.... however this would mean ignoring the npm `latest` tag, just using time stamps. 

Maybe this is a good thing based on the number of issues with this tag....

@xtuc
